In [2]:
import numpy as np  

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(5, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,4,5,6,7,8, 9, 10])

In [7]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multi dimentional arrays

In [9]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ])

In [ ]:
n[1][2]

np.int64(6)

In [15]:
n[1,2]

np.int64(6)

In [16]:
n[2] = [1, 1, 1]

In [ ]:
# second column
n[:, 1]

array([2, 5, 1])

In [19]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [23]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [ ]:
n + 1 # add 1 to all elements.

array([[2, 3, 4],
       [5, 6, 7],
       [2, 2, 2]])

In [ ]:
n*2 # multiple by 2 each element

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 2,  2,  2]])

In [26]:
b = (10 + (n*2)) **2 

In [27]:
n + b

array([[145, 198, 259],
       [328, 405, 490],
       [145, 145, 145]])

comparisons

In [28]:
a >= 2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [29]:
n > b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [33]:
n[b > n]

array([1, 2, 3, 4, 5, 6, 1, 1, 1])

In [34]:
a.min()

np.int64(1)

In [35]:
a.max()

np.int64(10)

In [38]:
n.std()

np.float64(1.8257418583505538)